version: '3'

services:
  travelservice:
    build: ./TravelService/
    container_name: travelservice
    networks:
      - travel_application
    ports:
      - 8090:8090
    depends_on:
      - mysql
#      - conductor-server
      - conductor-server-ui
      - elasticsearch
      - dynomite
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/conductor
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
#      CONDUCTOR_SERVER_URI: http://conductor-server:8080/api/
      CONDUCTOR_SERVER_URI: http://conductor-server-ui:8080/api/
#      SPRING_SLEUTH_ENABLED: "true"
#      SPRING_SLEUTH_SAMPLER_PROBABILITY: 1
#      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411/
#

  hotelservice:
    build: ./HotelService/
    container_name: hotelservice
    networks:
      - travel_application
    ports:
#      - 8082:8080
      - 8082:8082
    depends_on:
      - mysql
#      - conductor-server
      - conductor-server-ui
      - elasticsearch
      - dynomite
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/conductor
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
#      CONDUCTOR_SERVER_URI: http://conductor-server:8080/api/
      CONDUCTOR_SERVER_URI: http://conductor-server-ui:8080/api/
#      SPRING_SLEUTH_ENABLED: "true"
#      SPRING_SLEUTH_SAMPLER_PROBABILITY: 1
#      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411/


  flightservice:
    build: ./FlightService/
    container_name: flightservice
    networks:
      - travel_application
    ports:
      - 8083:8083
    depends_on:
      - mysql
#      - conductor-server
      - conductor-server-ui
      - elasticsearch
      - dynomite
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/conductor
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
#      CONDUCTOR_SERVER_URI: http://conductor-server:8080/api/
      CONDUCTOR_SERVER_URI: http://conductor-server-ui:8080/api/
#      SPRING_SLEUTH_ENABLED: "true"
#      SPRING_SLEUTH_SAMPLER_PROBABILITY: 1
#      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411/

#  conductor-server: #--> conductor Projekt
#    build: ./Conductor/
#    container_name: conductor-server
#    networks:
#      - travel_application
#    ports:
#      - 8080:8080
#    expose:
#      - '8080'
#    links:
#      - elasticsearch:es
#      - dynomite:dyno1
#    depends_on:
#      - elasticsearch
#      - dynomite
#    environment:
#      - CONFIG_PROP=config.properties

#  conductor-server: #--> aktuell mit exception
#    build:
#      context: ./conductor/conductorServer/
#      dockerfile: Dockerfile
#    image: conductor-server
#    container_name: conductor-server
#    networks:
#      - travel_application
#    ports:
#      - 8080:8080
#    expose:
#      - '8080'
#    links:
#      - elasticsearch:es
#      - dynomite:dyno1
#    depends_on:
#      - elasticsearch
#      - dynomite
#    environment:
#      - CONFIG_PROP=config.properties
##    logging:
##      driver: "json-file"
##      options:
##        max-size: "1k"
##        max-file: "3"
#
#  conductor-ui: # funktioniert aber eigentlich soll server-UI image verwendet werden
#    build:
#      context: ./conductor/conductorUi/
#      dockerfile: Dockerfile
#    image: conductor-ui
#    container_name: conductor-ui
#    networks:
#      - travel_application
#    ports:
#      - 5000:5000
#    links:
#      - conductor-server
#    depends_on:
#      - conductor-server
#    environment:
#      - WF_SERVER=http://conductor-server:8080/api/

  conductor-server-ui: #--> aktuell mit exception wenn nicht inmemory //TODO soll verwendet werden
    build:
      context: conductor/serverAndUi/
      dockerfile: Dockerfile
    image: conductor-server-ui
    container_name: conductor-server-ui
    networks:
      - travel_application
    ports:
      - 8080:8080
      - 5000:5000
    expose:
      - '8080'
      - '5000'
    links:
      - elasticsearch:es
      - dynomite:dyno1
    depends_on:
      - elasticsearch
      - dynomite
    environment:
#      - CONFIG_PROP=config.properties #// TODO --> oder doch inMemory ausreichend?
      - WF_SERVER=http://localhost:8080/api/
  #    logging:
  #      driver: "json-file"
  #      options:
  #        max-size: "1k"
  #        max-file: "3"

  dynomite:
    image: v1r3n/dynomite
    container_name: dynomite
    networks:
      - travel_application
    ports:
      - 8102:8102
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/8102'
      interval: 5s
      timeout: 5s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.6.8
      container_name: elasticsearch
      environment:
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - transport.host=0.0.0.0
        - discovery.type=single-node
        - xpack.security.enabled=false
      networks:
        - travel_application
      ports:
        - 9200:9200
        - 9300:9300
      healthcheck:
        test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/9300'
        interval: 5s
        timeout: 5s
        retries: 12
      logging:
        driver: "json-file"
        options:
          max-size: "1k"
          max-file: "3"

  mysql:
    image: library/mysql:5.6
    container_name: mysql
    restart: always
    volumes:
      - travel_db:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - travel_application
    expose:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=conductor
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw

#  zipkin:
#    image: openzipkin/zipkin
#    container_name: zipkin
#    ports:
#      - "9411:9411"
#    environment:
#      JAVA_OPTS: -Xmx64m

networks:
  travel_application:

volumes:
  travel_db:
