version: '3'

services:
  travelservice:
    build: ./TravelService/
    image: travelservice:microProfile
    container_name: travelservice_microProfile
    networks:
      - travel_application
    ports:
      - 8090:8090
    depends_on:
      - mysql
    environment:
      DEFAULT_HTTP_PORT: 8090
      DEFAULT_HTTPS_PORT: -1
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      OPENLIBERTY_MYSQL_USERNAME: mysqluser
      OPENLIBERTY_MYSQL_PASSWORD: mysqlpw
      LRA_COORDINATOR_PORT: 8080
      LRA_COORDINATOR_HOST: lraCoordinator
      LRA_COORDINATOR_PATH: lra/lra-coordinator
      FLIGHT_SERVICE_URI: flightservice
      HOTEL_SERVICE_URI: hotelservice

#  hotelservice:
#    build: ./HotelService/
#    image: hotelservice:microProfile
#    container_name: hotelservice_microProfile
#    networks:
#      - travel_application
#    ports:
#      - 8081:8081
#    depends_on:
#      - mysql
#      - conductor-server-ui
#      - elasticsearch
#      - dynomite
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/conductor
#      SPRING_DATASOURCE_USERNAME: mysqluser
#      SPRING_DATASOURCE_PASSWORD: mysqlpw
#      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
#      CONDUCTOR_SERVER_URI: http://conductor-server-ui:8080/api/
#
#
#  flightservice:
#    build: ./FlightService/
#    image: flightservice:microProfile
#    container_name: flightservice_microProfile
#    networks:
#      - travel_application
#    ports:
#      - 8082:8082
#    depends_on:
#      - mysql
#      - conductor-server-ui
#      - elasticsearch
#      - dynomite
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/conductor
#      SPRING_DATASOURCE_USERNAME: mysqluser
#      SPRING_DATASOURCE_PASSWORD: mysqlpw
#      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
#      CONDUCTOR_SERVER_URI: http://conductor-server-ui:8080/api/


  mysql:
    image: library/mysql:5.6
    container_name: mysql_microProfile
    restart: always
    volumes:
      - travel_db_microProfile:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - travel_application
    expose:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=microProfile
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw


networks:
  travel_application:

volumes:
  travel_db_microProfile:
