---
openapi: 3.0.3
info:
  title: LRA Coordinator
  version: 1.0-RC1
servers:
  - url: http://localhost:8090/lrac
    description: The server for the LRACoordinator endpoint.
  - url: http://localhost:8090/
tags:
  - name: LRA Coordinator
  - name: LRA Recovery
paths:
  /lra-coordinator:
    servers:
      - url: http://localhost:8090/lrac
    get:
      tags:
        - LRA Coordinator
      summary: Returns all LRAs
      description: Gets both active and recovering LRAs
      parameters:
        - name: Status
          in: query
          description: Filter the returned LRAs to only those in the give state (see
            CompensatorStatus)
          schema:
            default: ""
            type: string
      responses:
        default:
          description: The LRA
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LRAData'
  /lra-coordinator/nested/{NestedLraId}/compensate:
    servers:
      - url: http://localhost:8090/lrac
    put:
      tags:
        - LRA Coordinator
      parameters:
        - name: NestedLraId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
  /lra-coordinator/nested/{NestedLraId}/complete:
    servers:
      - url: http://localhost:8090/lrac
    put:
      tags:
        - LRA Coordinator
      parameters:
        - name: NestedLraId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
  /lra-coordinator/nested/{NestedLraId}/forget:
    servers:
      - url: http://localhost:8090/lrac
    put:
      tags:
        - LRA Coordinator
      parameters:
        - name: NestedLraId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
  /lra-coordinator/nested/{NestedLraId}/status:
    servers:
      - url: http://localhost:8090/lrac
    get:
      tags:
        - LRA Coordinator
      parameters:
        - name: NestedLraId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
  /lra-coordinator/start:
    servers:
      - url: http://localhost:8090/lrac
    post:
      tags:
        - LRA Coordinator
      summary: Start a new LRA
      description: "The LRA model uses a presumed nothing protocol: the coordinator\
        \ must communicate\nwith Compensators in order to inform them of the LRA activity.\
        \ Every time a\nCompensator is enrolled with a LRA, the coordinator must make\
        \ information about\nit durable so that the Compensator can be contacted when\
        \ the LRA terminates,\neven in the event of subsequent failures. Compensators,\
        \ clients and coordinators\ncannot make any presumption about the state of\
        \ the global transaction without\nconsulting the coordinator and all compensators,\
        \ respectively."
      parameters:
        - name: ClientID
          in: query
          description: Each client is expected to have a unique identity (which can
            be a URL).
          required: true
          schema:
            default: ""
            type: string
        - name: ParentLRA
          in: query
          description: The enclosing LRA if this new LRA is nested
          schema:
            default: ""
            type: string
        - name: TimeLimit
          in: query
          description: "Specifies the maximum time in milli seconds that the LRA will\
          \ exist for.\nIf the LRA is terminated because of a timeout, the LRA URL\
          \ is deleted.\nAll further invocations on the URL will return 404.\nThe\
          \ invoker can assume this was equivalent to a compensate operation."
          schema:
            format: int64
            default: "0"
            type: integer
        - name: Long-Running-Action
          in: header
          schema:
            type: string
      responses:
        "201":
          description: The request was successful and the response body contains the
            id of the new LRA
          content:
            text/plain:
              schema:
                title: An LRA id
                description: An URI of the new LRA
        "500":
          description: A new LRA could not be started
  /lra-coordinator/{LraId}:
    servers:
      - url: http://localhost:8090/lrac
    get:
      tags:
        - LRA Coordinator
      summary: Obtain the status of an LRA as a JSON structure
      parameters:
        - name: LraId
          in: path
          description: The unique identifier of the LRA
          required: true
          schema:
            type: string
      responses:
        "404":
          description: The coordinator has no knowledge of this LRA
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LRAData'
        "204":
          description: The LRA exists and has not yet been asked to close or cancel
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LRAData'
        "200":
          description: The LRA exists. The status is reported in the content body.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LRAData'
    put:
      tags:
        - LRA Coordinator
      summary: A Compensator can join with the LRA at any time prior to the completion
        of an activity
      parameters:
        - name: LraId
          in: path
          description: The unique identifier of the LRA
          required: true
          schema:
            type: string
        - name: TimeLimit
          in: query
          description: "The time limit (in seconds) that the Compensator can guarantee\
          \ that it can compensate the work performed by the service. After this time\
          \ period has elapsed, it may no longer be possible to undo the work within\
          \ the scope of this (or any enclosing) LRA. It may therefore be necessary\
          \ for the application or service to start other activities to explicitly\
          \ try to compensate this work. The application or coordinator may use this\
          \ information to control the lifecycle of a LRA."
          schema:
            format: int64
            default: 0
            type: integer
        - name: Link
          in: header
          description: "The resource paths that the coordinator will use to complete\
          \ or compensate and to request the status of the participant. The link rel\
          \ names are complete, compensate and status."
          schema:
            default: ""
            type: string
      requestBody:
        description: |
          opaque data that will be stored with the coordinator and passed back to
          the participant when the LRA is closed or cancelled.
        content:
          '*/*':
            schema:
              type: string
      responses:
        "404":
          description: The coordinator has no knowledge of this LRA
        "412":
          description: The LRA is not longer active (ie in the complete or compensate
            messages have been sent
        "200":
          description: |-
            The participant was successfully registered with the LRA and the response body contains a unique resource reference for that participant:
             - HTTP GET on the reference returns the original participant URL;
             - HTTP PUT on the reference will overwrite the old participant URL with the new one supplied.
          headers:
            Long-Running-Action-Recovery:
              description: |-
                If the participant is successfully registered with the LRA then this header
                 will contain a unique resource reference for that participant:
                 - HTTP GET on the reference returns the original participant URL;
                 - HTTP PUT on the reference will overwrite the old participant URL with the new one supplied.
              style: simple
              schema:
                type: string
          content:
            application/json:
              schema:
                title: A new LRA recovery id
                description: An URI representing the recovery id of this join request
  /lra-coordinator/{LraId}/cancel:
    servers:
      - url: http://localhost:8090/lrac
    put:
      tags:
        - LRA Coordinator
      summary: Attempt to cancel an LRA
      description: " Trigger the compensation of the LRA. All compensators will be\
        \ triggered by the coordinator (ie the compensate message will be sent to\
        \ each compensators). Upon termination, the URL is implicitly deleted. The\
        \ invoker cannot know for sure whether the lra completed or compensated without\
        \ enlisting a participant."
      parameters:
        - name: LraId
          in: path
          description: The unique identifier of the LRA
          required: true
          schema:
            type: string
      responses:
        "404":
          description: The coordinator has no knowledge of this LRA
        "200":
          description: The compensate message was sent to all coordinators
          content:
            application/json:
              schema:
                title: one of the LRAStatus enum values
                type: string
  /lra-coordinator/{LraId}/close:
    servers:
      - url: http://localhost:8090/lrac
    put:
      tags:
        - LRA Coordinator
      summary: Attempt to close an LRA
      description: "Trigger the successful completion of the LRA. All compensators\
        \ will be dropped by the coordinator. The complete message will be sent to\
        \ the compensators. Upon termination, the URL is implicitly deleted. The invoker\
        \ cannot know for sure whether the lra completed or compensated without enlisting\
        \ a participant."
      parameters:
        - name: LraId
          in: path
          description: The unique identifier of the LRA
          required: true
          schema:
            type: string
      responses:
        "404":
          description: The coordinator has no knowledge of this LRA
        "200":
          description: The complete message was sent to all coordinators
          content:
            text/plain:
              schema:
                title: one of the LRAStatus enum values
                type: string
  /lra-coordinator/{LraId}/remove:
    servers:
      - url: http://localhost:8090/lrac
    put:
      tags:
        - LRA Coordinator
      summary: A Compensator can resign from the LRA at any time prior to the completion
        of an activity
      parameters:
        - name: LraId
          in: path
          description: The unique identifier of the LRA
          required: true
          schema:
            type: string
      responses:
        "404":
          description: The coordinator has no knowledge of this LRA
        "412":
          description: The LRA is not longer active (ie in the complete or compensate
            messages have been sent
        "200":
          description: If the participant was successfully removed from the LRA
  /lra-coordinator/{LraId}/renew:
    servers:
      - url: http://localhost:8090/lrac
    put:
      tags:
        - LRA Coordinator
      summary: Update the TimeLimit for an existing LRA
      description: |
        LRAs can be automatically cancelled if they aren't closed or cancelled before the TimeLimit
        specified at creation time is reached.
        The time limit can be updated.
      parameters:
        - name: LraId
          in: path
          required: true
          schema:
            type: string
        - name: TimeLimit
          in: query
          description: The new time limit for the LRA
          required: true
          schema:
            format: int64
            default: "0"
            type: integer
      responses:
        "200":
          description: If the LRA timelimit has been updated
        "404":
          description: The coordinator has no knowledge of this LRA
        "412":
          description: The LRA is not longer active (ie the complete or compensate
            messages have been sent
  /lra-coordinator/{LraId}/status:
    servers:
      - url: http://localhost:8090/lrac
    get:
      tags:
        - LRA Coordinator
      summary: Obtain the status of an LRA as a string
      parameters:
        - name: LraId
          in: path
          description: The unique identifier of the LRA
          required: true
          schema:
            type: string
      responses:
        "404":
          description: The coordinator has no knowledge of this LRA
        "204":
          description: The LRA exists and has not yet been asked to close or cancel
        "200":
          description: The LRA exists. The status is reported in the content body.
  /lra-recovery-coordinator/failed:
    servers:
      - url: http://localhost:8090/lrac
  servers:
    url: http://localhost:8090/lrac
    get:
      tags:
        - LRA Recovery
      summary: List failed Long Running Actions
      description: Returns LRAs that have failed.  Failure records are vital pieces
        of data needed to aid failure tracking and analysis  and are retained for
        inspection.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LRAStatusHolder'
  /lra-recovery-coordinator/recovery:
    servers:
      - url: http://localhost:8090/lrac
    get:
      tags:
        - LRA Recovery
      summary: List recovering Long Running Actions
      description: Returns LRAs that are recovering (ie some compensators still need
        to be ran)
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LRAStatusHolder'
  /lra-recovery-coordinator/{LRAId}/{RecCoordId}:
    servers:
      - url: http://localhost:8090/lrac
    get:
      tags:
        - LRA Recovery
      summary: Lookup the participant URL
      description: Performing a GET on the recovery URL (returned from a join request)
        will return the original participant URL(s)
      parameters:
        - name: LRAId
          in: path
          description: Identifies the LRAId that the participant joined
          required: true
          schema:
            type: string
        - name: RecCoordId
          in: path
          description: An identifier that was returned by the coordinator when a participant
            joined the LRA
          required: true
          schema:
            type: string
      responses:
        "404":
          description: The coordinator has no knowledge of this participant
        "200":
          description: The participant associated with this recovery id is returned
          content:
            application/json:
              schema:
                title: The original participant URI
    put:
      tags:
        - LRA Recovery
      summary: Update the endpoint that a participant is prepared to accept requests
        on.
      description: Performing a PUT on the recovery URL will overwrite the old <compensor
        URL> with the new one supplied and return the old url. The old value is returned.The
        full URL was returned when the participant first joined the LRA.
      parameters:
        - name: LRAId
          in: path
          description: Identifies the LRAId that the participant joined
          required: true
          schema:
            type: string
        - name: RecCoordId
          in: path
          description: An identifier that was returned by the coordinator when a participant
            joined the LRA
          required: true
          schema:
            type: string
      responses:
        "404":
          description: The coordinator has no knowledge of this participant
        "200":
          description: The coordinator has replaced the old participant with the new
            one
          content:
            application/json:
              schema:
                type: string
  /lra-recovery-coordinator/{LraId}:
    servers:
      - url: http://localhost:8090/lrac
    delete:
      tags:
        - LRA Recovery
      summary: Remove the log for a failed LRA
      parameters:
        - name: LraId
          in: path
          description: The unique identifier of the LRA
          required: true
          schema:
            type: string
      responses:
        "204":
          description: If the LRA log was successfully removed
        "412":
          description: If the input LRA does not correspond to a valid URI (in which
            case the response entity will contain the error message)
        "500":
          description: If the attempt to remove the LRA log failed. This return code
            does not discriminate between a failure at the log storage level or if
            the log did not exist)
components:
  schemas:
    LRAStatusHolder:
      type: object
      properties:
        clientId:
          type: string
        failedParticipants:
          type: array
          items:
            type: string
        finishTime:
          format: int64
          type: integer
        httpStatus:
          format: int32
          type: integer
        isActive:
          type: boolean
        isRecovering:
          type: boolean
        isTopLevel:
          type: boolean
        lraId:
          type: string
        lraStatus:
          type: object
        responseData:
          type: string
        startTime:
          format: int64
          type: integer
        timeNow:
          format: int64
          type: integer
        encodedResponseData:
          type: string
        status:
          type: object
        active:
          type: boolean
        cancelled:
          type: boolean
        cancelling:
          type: boolean
        closed:
          type: boolean
        closing:
          type: boolean
        failedToCancel:
          type: boolean
        failedToClose:
          type: boolean
        recovering:
          type: boolean
        topLevel:
          type: boolean
    LRAData:
      type: object
      properties:
        clientId:
          type: string
        finishTime:
          format: int64
          type: integer
        isActive:
          type: boolean
        isCancelled:
          type: boolean
        isClosed:
          type: boolean
        isRecovering:
          type: boolean
        isTopLevel:
          type: boolean
        lraId:
          type: string
        startTime:
          format: int64
          type: integer
        status:
          type: string
        timeNow:
          format: int64
          type: integer
        zoneOffset:
          type: object
        active:
          type: boolean
        cancelled:
          type: boolean
        closed:
          type: boolean
        recovering:
          type: boolean
        topLevel:
          type: boolean